### ISSUE TITLE
PHPUnit tests fail when iddqd plugin required

### ISSUE THREAD

**Issue by dersam** [linusshops/prophet#62]
Run `prophet` to view error.

Fatal error: Uncaught InvalidArgumentException: Unknown output type given (16) in /Users/samuelschmidt/boxes/develop/sites/prophet/plugins/prophet-plugin-iddqd/vendor/symfony/console/Output/Output.php:147
Stack trace:
#0 /Users/samuelschmidt/boxes/develop/sites/prophet/plugins/prophet-plugin-iddqd/vendor/symfony/console/Output/Output.php(122): Symfony\Component\Console\Output\Output->write(Array, true, 16)
#1 /Users/samuelschmidt/boxes/develop/sites/prophet/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln('', 16)
#2 /Users/samuelschmidt/boxes/develop/sites/prophet/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(CredisException), Object(Symfony\Component\C

**Comment by dersam** [comment]
Need to provide an event that only fires in isolated processes. This should then be used by the IDDQD plugin, which is the root cause of this issue.

**Comment by dersam** [comment]
Depends on #65
